import type { AchievementKind, AchievementView } from "@/lib/types";

export type AchievementDefinition = Omit<AchievementView, "progress" | "unlocked" | "unlockedAt">;

export const achievementCatalog: AchievementDefinition[] = [
  {
    key: "first-step",
    title: "Первый шаг",
    description: "Совершить первую зачтённую продажу в сезоне.",
    story: "Первый след появился на золотой тропе. Саванна запомнила начало твоего пути.",
    symbol: "✦",
    kind: "sales",
    color: "#e8b13f",
    target: 1,
    cosmeticTier: 0,
  },
  {
    key: "strong-week",
    title: "Сильная неделя",
    description: "Совершить 3 зачтённые продажи за любые 7 дней.",
    story: "Три ярких следа соединились в одну уверенную тропу. Прайд чувствует твой ритм.",
    symbol: "🔥",
    kind: "rhythm",
    color: "#df7044",
    target: 3,
    cosmeticTier: 0,
  },
  {
    key: "return-to-savanna",
    title: "Возвращение в саванну",
    description: "Совершить продажу после паузы в 14 дней.",
    story: "После долгой тишины твой шаг снова слышен в саванне. Возвращение состоялось.",
    symbol: "☀",
    kind: "rhythm",
    color: "#df8d3d",
    target: 1,
    cosmeticTier: 0,
  },
  {
    key: "always-moving",
    title: "Всегда в движении",
    description: "Провести 7 дней без сгоревших бросков и использовать хотя бы один бросок.",
    story: "Ни один шанс не потерян. Твой путь идёт в точном ритме золотого солнца.",
    symbol: "➶",
    kind: "rhythm",
    color: "#65a890",
    target: 7,
    cosmeticTier: 0,
  },
  {
    key: "fast-start",
    title: "Быстрый старт",
    description: "Совершить 3 зачтённые продажи за первые 7 суток сезона.",
    story: "Сезон только начался, а твой след уже сияет на тропе. Прайд чувствует уверенный старт.",
    symbol: "⚡",
    kind: "sales",
    color: "#e2a52d",
    target: 3,
    cosmeticTier: 0,
  },
  {
    key: "dawn-streak",
    title: "Серия рассветов",
    description: "Совершать минимум одну продажу 3 календарных дня подряд.",
    story: "Три рассвета подряд саванна встречала твой новый след. Так рождается настоящий ритм.",
    symbol: "🌅",
    kind: "rhythm",
    color: "#e47845",
    target: 3,
    cosmeticTier: 0,
  },
  {
    key: "pride-rhythm",
    title: "Ритм прайда",
    description: "Совершить продажи в 5 разных календарных дней сезона.",
    story: "Твой путь не вспышка, а устойчивый ритм. Пять дней стали пятью сильными главами.",
    symbol: "♫",
    kind: "rhythm",
    color: "#49a68f",
    target: 5,
    cosmeticTier: 0,
  },
  {
    key: "royal-week",
    title: "Королевская неделя",
    description: "Совершить 5 зачтённых продаж за любые последовательные 7 суток.",
    story: "Пять побед за одну неделю зажгли над тропой королевское золотое сияние.",
    symbol: "💛",
    kind: "sales",
    color: "#d8a51f",
    target: 5,
    cosmeticTier: 0,
  },
  {
    key: "no-losses",
    title: "Без потерь",
    description: "Использовать 10 бросков подряд, не допустив сгорания между ними.",
    story: "Ни один шанс не растворился в песках. Десять бросков превратились в безупречную серию.",
    symbol: "◉",
    kind: "rhythm",
    color: "#4d9f78",
    target: 10,
    cosmeticTier: 0,
  },
  {
    key: "just-in-time",
    title: "Точно в срок",
    description: "Использовать бросок, когда до его сгорания осталось не более 3 часов.",
    story: "Последние песчинки почти упали, но решающий шаг сделан точно в срок.",
    symbol: "⏳",
    kind: "rhythm",
    color: "#c7833b",
    target: 1,
    cosmeticTier: 0,
  },
  {
    key: "treasure-seeker",
    title: "Искатель сокровищ",
    description: "Получить первое сокровище на карте в текущем сезоне.",
    story: "Первый сундук открылся, и золотой свет озарил твою дорогу.",
    symbol: "✦",
    kind: "treasure",
    color: "#e3ae32",
    target: 1,
    cosmeticTier: 0,
  },
  {
    key: "savanna-collector",
    title: "Коллекционер саванны",
    description: "Получить 3 сокровища на карте за один сезон.",
    story: "Три сокровища собраны в одну коллекцию. Теперь о ней знает вся саванна.",
    symbol: "◆",
    kind: "treasure",
    color: "#c88d29",
    target: 3,
    cosmeticTier: 0,
  },
  {
    key: "wind-master",
    title: "Повелитель ветра",
    description: "Дважды остановиться на клетке ускорения за сезон.",
    story: "Золотой ветер дважды подхватил тебя — теперь он узнаёт твой шаг.",
    symbol: "➶",
    kind: "adventure",
    color: "#58a99f",
    target: 2,
    cosmeticTier: 0,
  },
  {
    key: "unshakable",
    title: "Несгибаемый дух",
    description: "Трижды встретить препятствие и продолжить путь в том же сезоне.",
    story: "Камни замедляли путь, но не смогли остановить тебя. Саванна признаёт твою стойкость.",
    symbol: "⬢",
    kind: "adventure",
    color: "#8d7563",
    target: 3,
    cosmeticTier: 0,
  },
  {
    key: "mystery-explorer",
    title: "Исследователь тайн",
    description: "Открыть 3 сюжетных события на карте за сезон.",
    story: "Три тайны саванны доверились тебе и стали частью личной летописи.",
    symbol: "?",
    kind: "adventure",
    color: "#5da7bf",
    target: 3,
    cosmeticTier: 0,
  },
  {
    key: "trial-conqueror",
    title: "Покоритель испытаний",
    description: "Выполнить 3 задания, подтверждённых руководителем.",
    story: "Три испытания завершены честно и уверенно. Перед тобой открывается новая тропа.",
    symbol: "✓",
    kind: "task",
    color: "#9567b1",
    target: 3,
    cosmeticTier: 0,
  },
  {
    key: "client-voice",
    title: "Голос клиента",
    description: "Выполнить подтверждённое задание с честным положительным отзывом клиента.",
    story: "Добрые слова клиента стали голосом, который услышала вся саванна.",
    symbol: "♥",
    kind: "task",
    color: "#d49b32",
    target: 1,
    cosmeticTier: 0,
  },
  {
    key: "pride-face",
    title: "Лицо прайда",
    description: "Выполнить подтверждённое задание с фотографией с клиентом.",
    story: "Тёплый кадр сохранил момент доверия — теперь он сияет в истории прайда.",
    symbol: "◍",
    kind: "task",
    color: "#d5767f",
    target: 1,
    cosmeticTier: 0,
  },
  {
    key: "final-sprint",
    title: "Финальный рывок",
    description: "Продвинуться суммарно минимум на 12 клеток за 3 последовательных броска.",
    story: "Три броска слились в один мощный рывок. Пыль ещё не осела, а ты уже далеко впереди.",
    symbol: "➤",
    kind: "adventure",
    color: "#df7545",
    target: 12,
    cosmeticTier: 0,
  },
  {
    key: "pride-keeper",
    title: "Хранитель прайда",
    description: "Совершить 5 зачтённых продаж за сезон.",
    story: "Пять побед укрепили прайд. Теперь твой голос узнают далеко за пределами тропы.",
    symbol: "🦁",
    kind: "sales",
    color: "#d49b32",
    target: 5,
    cosmeticTier: 0,
  },
  {
    key: "savanna-scout",
    title: "Следопыт саванны",
    description: "Совершить 10 зачтённых продаж за сезон.",
    story: "Ты читаешь золотые тропы как открытую книгу и уверенно ведёшь путь вперёд.",
    symbol: "◈",
    kind: "sales",
    color: "#4c9a78",
    target: 10,
    cosmeticTier: 0,
  },
  {
    key: "golden-trail",
    title: "Золотой след",
    description: "Совершить 15 зачтённых продаж за сезон.",
    story: "За тобой остаётся сияющий след, который вдохновляет весь прайд.",
    symbol: "✺",
    kind: "sales",
    color: "#d5aa31",
    target: 15,
    cosmeticTier: 0,
  },
  {
    key: "royal-strength",
    title: "Королевская сила",
    description: "Совершить 20 зачтённых продаж за сезон.",
    story: "Двадцать побед превратили уверенность в настоящую королевскую силу.",
    symbol: "♛",
    kind: "sales",
    color: "#9f6ac1",
    target: 20,
    cosmeticTier: 0,
  },
  {
    key: "chapter-pride-trail",
    title: "Голос прайда",
    description: "Достичь 15-й клетки и пройти главу «Тропа прайда».",
    story: "Тропа прайда пройдена. С вершины холма впервые звучит твой уверенный рык.",
    symbol: "☀",
    kind: "chapter",
    color: "#e3a82f",
    target: 15,
    cosmeticTier: 1,
  },
  {
    key: "chapter-watering-place",
    title: "Хранитель водопоя",
    description: "Достичь 30-й клетки и пройти главу «Земли у водопоя».",
    story: "Воды саванны отражают твоё новое сияние. Вторая глава пути завершена.",
    symbol: "◆",
    kind: "chapter",
    color: "#45a6ad",
    target: 30,
    cosmeticTier: 2,
  },
  {
    key: "chapter-heir-rock",
    title: "Зов Вершины",
    description: "Достичь 45-й клетки и пройти главу «Испытание саванны».",
    story: "Вершина уже видна впереди. Саванна признаёт силу пройденного пути.",
    symbol: "♛",
    kind: "chapter",
    color: "#b976cf",
    target: 45,
    cosmeticTier: 3,
  },
];

export const achievementByKey = new Map(achievementCatalog.map((achievement) => [achievement.key, achievement]));

export const chapterDefinitions = [
  { from: 1, to: 15, title: "Тропа прайда", shortTitle: "Глава I", color: "#d89b2b", marker: { x: 315, y: 850 } },
  { from: 16, to: 30, title: "Земли у водопоя", shortTitle: "Глава II", color: "#3c9fa4", marker: { x: 1460, y: 735 } },
  { from: 31, to: 45, title: "Испытание саванны", shortTitle: "Глава III", color: "#8b5d9f", marker: { x: 160, y: 445 } },
  { from: 46, to: 59, title: "Подъём к Вершине", shortTitle: "Глава IV", color: "#bd712e", marker: { x: 1440, y: 182 } },
  { from: 60, to: 60, title: "Коронация", shortTitle: "Финал", color: "#d4a52f", marker: { x: 1590, y: 68 } },
];

export function achievementKindLabel(kind: AchievementKind) {
  if (kind === "chapter") return "Титул главы";
  if (kind === "rhythm") return "Ритм сезона";
  if (kind === "treasure") return "Сокровища";
  if (kind === "adventure") return "Приключения";
  if (kind === "task") return "Испытания";
  return "Продажи";
}
